import Head from 'next/head';
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
  Line,
  Subheader,
} from '../components/sharedstyles';
import { Suspense } from 'react';
import Video from '@/components/Video/Video';
import Hero from '@/containers/Hero/HeroContainer';
import Mission from '@/containers/Mission/MissionContainer';
import Quote from '@/containers/Quote/QuoteContainer';
import Faqs from '@/containers/Faqs/FaqsContainer';
import CTA from '@/containers/CTA/CTAContainer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Merrimack Valley Spartans</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Mission />
      <Quote />
      <Faqs />
    </>
  );
}
